### ISSUE TITLE
Crashes whenever a turtle is rendered

### ISSUE THREAD

**Issue by mattguy0304** [JheffersonMarques/TurtleCosmetics#2]
[Forge] CC Cosmetics 1.1 crashes whenever a turtle is rendered on cc-tweaked-1.20.1 versions 1.109.3 through 1.111.0
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-07-28 15:24:23
Description: Rendering Block Entity

java.lang.NoSuchMethodError: 'net.minecraft.resources.ResourceLocation dan200.computercraft.client.render.TurtleBlockEntityRenderer.getTurtleModel(dan200.computercraft.shared.computer.core.ComputerFamily, boolean)'
	at dan200.computercraft.client.render.TurtleBlockEntityRenderer.render(TurtleBlockEntityRenderer.java:590) ~[cc-tweaked-1.20.1-forge-1.109.3.jar%23158!/:1.109.3] {re:mixin,re:classloading,pl:mixin:APP:TurtleCosmetics.mixins.json:TurtleRenderingMixin,pl:mixin:A}
	at dan200.computercraft.client.render.TurtleBlockEntityRenderer.m_6922_(TurtleBlockEntityRenderer.java:29) ~[cc-tweaked-1.20.1-forge-1.109.3.jar%23158!/:1.109.3] {re:mixin,re:classloading,pl:mixin:APP:TurtleCosmetics.mixins.json:TurtleRenderingMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:90) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112297_(BlockEntityRenderDispatcher.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1262) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```
I think it's the same issue that SquidDev opened here: https://github.com/JheffersonMarques/TurtleCosmetics/issues/1

**Comment by LieutenantTeaTM** [comment]
I'm having the exact same issue. I'm running CC: Tweaked version 1.114.2, forge 1.20.1 and [Forge] CC Cosmetics 1.1. From what I gather the only options are to use Fabric or downgrade. It is unfortunate, I really want this mod to work! But I am already so far into my survival world that it would likely break something.

Also from what I gather there hasn't been a commit here to 1.2, despite being a released version, but maybe I'm missing something. So it is more difficult to fork.

**Comment by minecraftbossdj** [comment]
hi! i uh plan on updating this mod, and will make a pull request, i hope he accepts, I do like this mod very much and I missed when it worked

**Comment by minecraftbossdj** [comment]
(i know im very late)

**Comment by minecraftbossdj** [comment]
this should be fixed in 1.20.1, and usuable in 1.115.x+ after #3

**Comment by minecraftbossdj** [comment]
you do have to compile the mod yourself though

**Comment by minecraftbossdj** [comment]
unfortunately i dont have access to the fabric version, otherwise id update it too, i loved using this mod on sc3, and would love to on rcc
